swagger: "2.0"

info:
  description: "This is the server implementation for [EVIAGI](https://github.com/ParadauxIO/EVIAGI). EVIAGI stands for Electronic Voting is a *great* idea, and allows for the online orchestration and management of elections, electorates and constituencies."
  version: "1.0.0"
  title: "EVIAGI"
  termsOfService: "https://paradaux.io/404"
  contact:
    email: "eviagi-devs@paradaux.io"
  license:
    name: "AGPL 3.0"
    url: "https://www.gnu.org/licenses/agpl-3.0.en.html"
host: "server.eviagi.paradaux.io"
basePath: "/va/"
tags:
  - name: "source"
    description: "Source Code"
    externalDocs:
      description: "on Github"
      url: "https://github.com/ParadauxIO/EVIAGI"
  - name: "docs"
    description: "Additional Server Documentation"
schemes:
  - "https"
paths: {}